<template>
  <Bar :chart-options="chartOptions" :chart-data="chartData" :plugins="plugins" />
  <!-- time: {{ monitors[0].time }}
   solar: {{ monitors[0].solar }}
   generated_energy: {{ monitors[0].generated_energy }}
   perchased_energy: {{ monitors[0].perchased_energy }}
   accumulated_energy: {{ monitors[0].accumulated_energy }}
   consumption_energy: {{ monitors[0].consumption_energy }}
   selected_prediction_energy: {{ monitors[0].selected_prediction_energy }} -->
</template>

<script>
// import { Line } from "vue-chartjs";
import { Bar } from 'vue-chartjs'
import {
  Chart as ChartJS,
  Title,
  Tooltip,
  Legend,
  LineElement,
  LinearScale,
  PointElement,
  CategoryScale,
  Filler,
  BarElement,
} from "chart.js";

ChartJS.register(
  Title,
  Tooltip,
  Legend,
  LineElement,
  LinearScale,
  PointElement,
  CategoryScale,
  Filler,
  BarElement,
);

export default {
  components: {
    Bar,
  },
  data() {
    return {
      chartData: {
        labels: [
          "0",
          "1",
          "2",
          "3",
          "0",
          "1",
          "2",
          "3",
          "0",
          "1",
          "2",
          "3",
          "0",
          "1",
          "2",
          "3",
          "0",
          "1",
          "2",
          "3",
          "0",
          "1",
          "2",
          "3",
          "0",
          "1",
          "2",
          "3",
          "0",
          "1",
          "2",
          "3",
        ],
        datasets: [
          // PV交流電力量(kWh)
          {
            label: "PV交流電力量(kWh)",
            pointStyle: "rect",
            backgroundColor: "#FFFF00",
            data: [
              1, 2, 3, 4,
              1, 2, 3, 4,
              1, 2, 3, 4,
              1, 2, 3, 4,
              1, 2, 3, 4,
              1, 2, 3, 4,
              1, 2, 3, 4,
              1, 2, 3, 4,
            ],
          },
          // 売電電力量(kWh)
          {
            label: "売電電力量(kWh)",
            pointStyle: "rect",
            backgroundColor: "#00FF00",

            data: [
              4, 3, 2, 2,
              4, 3, 2, 2,
              4, 3, 2, 2,
              4, 3, 2, 2,
              4, 3, 2, 2,
              4, 3, 2, 2,
              4, 3, 2, 2,
              4, 3, 2, 2,
            ],
          },
          // 購入電力量(kWh)
          {
            label: "購入電力量(kWh)",
            pointStyle: "rect",
            backgroundColor: "#FF00FF",

            data: [
              4, 3, 2, 2,
              4, 3, 2, 2,
              4, 3, 2, 2,
              4, 3, 2, 2,
              4, 3, 2, 2,
              4, 3, 2, 2,
              4, 3, 2, 2,
              4, 3, 2, 2,
            ],
          },
          // 斜面日射量(kWh/m2)
          {
            label: "斜面日射量(kWh/m2)",
            pointStyle: "rect",
            type: "line",
            fill: "start",
            tension: 0.4,
            backgroundColor: "#4F4D1F99",
            borderColor: "#FFFFFF66",
            borderWidth: 2,

            data: [
              0, 5, 3, 1,
              0, 5, 3, 1,
              0, 5, 3, 1,
              0, 5, 3, 1,
              0, 5, 3, 1,
              0, 5, 3, 1,
              0, 5, 3, 1,
              0, 5, 3, 1,
            ],

          },
          {
            label: "Line1 Dataset",
            type: "line",
            tension: 0.4,
            borderColor: "#FFFFFF",
            borderWidth: 1,
            borderDash: [2, 1],  // 선과 빈공간 비율
            pointStyle: "dash",
            data: [
              5, 3, 2, 1,
              5, 3, 2, 1,
              5, 3, 2, 1,
              5, 3, 2, 1,
              5, 3, 2, 1,
              5, 3, 2, 1,
              5, 3, 2, 1,
              5, 3, 2, 1,
            ],

          },
        ],
      },
      chartOptions: {
        responsive: true,
        maintainAspectRatio: false,
        interaction: {
          mode: "index",
          intersect: false,
        },
        scales: {
        },
        plugins: {
          tooltip: {
            enabled: true,
          },
          legend: {
            // position: "chartArea",
            position: "top",
            align: "end",
            labels: {
              usePointStyle: true,
              // padding: 10
            }
          },
        },
      },
      monitors: [
        {
          time: 0,
          solar: 501.25,
          generated_energy: 111.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 0.5,
          solar: 501.25,
          generated_energy: 112.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 1,
          solar: 501.25,
          generated_energy: 113.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 1.5,
          solar: 501.25,
          generated_energy: 114.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 2.0,
          solar: 501.25,
          generated_energy: 115.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 2.5,
          solar: 501.25,
          generated_energy: 116.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 3,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 3.5,
          solar: 501.25,
          generated_energy: 118.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 4,
          solar: 501.25,
          generated_energy: 119.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 4.5,
          solar: 501.25,
          generated_energy: 111.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 5,
          solar: 501.25,
          generated_energy: 117.151,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 5.5,
          solar: 501.25,
          generated_energy: 117.153,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 6,
          solar: 501.25,
          generated_energy: 117.155,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 6.5,
          solar: 501.25,
          generated_energy: 117.157,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 7,
          solar: 501.25,
          generated_energy: 117.159,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 7.5,
          solar: 501.25,
          generated_energy: 117.151,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 8,
          solar: 501.25,
          generated_energy: 117.111,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 8.5,
          solar: 501.25,
          generated_energy: 117.1,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 9,
          solar: 501.25,
          generated_energy: 117.12,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 9.5,
          solar: 501.25,
          generated_energy: 117.123,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 10,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 10.5,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 11,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 11.5,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 12,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 12.5,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 13,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 13.5,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 14,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 14.5,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 15,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 15.5,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 16,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 16.5,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 17,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 17.5,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 18,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 18.5,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 19,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 19.5,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 20,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 20.5,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 21,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 21.5,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 22,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 22.5,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 23,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
        {
          time: 23.5,
          solar: 501.25,
          generated_energy: 117.152,
          perchased_energy: 0,
          accumulated_energy: 117.152,
          consumption_energy: 0,
          selected_prediction_energy: 115.0,
        },
      ],
    };
  },
  mounted() {
    this.setLabels();
  },
  methods: {
    setLabels() {
    }
  }
};
</script>

<style>
</style>
